# Generated by Django 5.1.4 on 2025-02-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
